# Generated by Django 2.0 on 2019-11-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_node', '0003_auto_20191102_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WriteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_key', models.CharField(max_length=100)),
                ('data_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SelfID',
        ),
    ]
