# Generated by Django 2.0 on 2019-11-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockstamps',
            name='time_stamp',
            field=models.IntegerField(default=0),
        ),
    ]
