# Generated by Django 2.0 on 2019-11-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_node', '0002_auto_20191102_0837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClockStamps',
            new_name='ClockStamp',
        ),
        migrations.RenameModel(
            old_name='StorageServers',
            new_name='StorageServer',
        ),
    ]
