# Generated by Django 2.0 on 2019-11-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageServers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField()),
                ('server_port', models.IntegerField()),
                ('server_down', models.BooleanField(default=True)),
            ],
        ),
    ]
