# Generated by Django 2.0 on 2019-11-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorageServers',
            new_name='StorageServer',
        ),
    ]
